#
# This file is an example of SonataTranslation configuration
# You should create your own for your project and add it in app/config/bundles/sonata_translation.yml
#
imports:
    - { resource: '@SonataTranslationBundle/Resources/config/config.yml'}

sonata_translation:
    locales: [fr, en, it, nl, es]
    default_locale: fr
